[package]
name = "rivertalk"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
futures = "0.3.30"
json = "0.12.4"
slint = "1.6.0"

[dependencies.async-std]
version = "1.6"
features = ["attributes"]

[build-dependencies]
slint-build = "1.6"
