import { LineEdit, Button, ScrollView, TextEdit } from "std-widgets.slint";
import { SideBar } from "../lib/side_bar.slint";
import { MessagePage, ProfilePage } from "pages/index.slint";

export component ClientUI inherits Window {
    // callback request-increase-value();
    min-height: 300px;
    min-width: 500px;
    title: "RiverTalk";
    HorizontalLayout {
        side-bar := SideBar {
            title: "Client";
            model: [@tr("Menu" => "Messages"), @tr("Menu" => "Profile")];
        }

        if(side-bar.current-item == 0): MessagePage { }
        if(side-bar.current-item == 1): ProfilePage { }
    }
}
